version: '3.1'

services:
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
      - redis
      - aws
    command: redis:6379 aws:4100 db:1433
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
  aws:
    image: pafortin/goaws
    ports:
    - "4100:4100"

